Fix warnings from -Wall
I use 4.1.1 and see warnings during build:

as.c: In function 'as_sleep':
as.c:732: warning: unused variable 'end'
conn.c: In function 'conn_mainloop_quit':
conn.c:95: warning: control reaches end of non-void function
mpdscribble.c: In function 'main':
mpdscribble.c:156: warning: implicit declaration of function 'chdir'
mpdscribble.c: In function 'main':
mpdscribble.c:157: warning: ignoring return value of 'chdir', declared
with
attribute warn_unused_result
lmc.c: In function 'lmc_failure':
lmc.c:42: warning: suggest parentheses around comparison in operand of
|
mbid.c: In function 'getOGG_MBID':
mbid.c:153: warning: unused variable 'bytes'
mbid.c: In function 'read_flac_block':
mbid.c:203: warning: unused variable 'bytes'
mbid.c:206: warning: ignoring return value of 'fread', declared with
attribute warn_unused_result
mbid.c: In function 'getMP3_MBID':
mbid.c:314: warning: unused variable 'version_minor'
mbid.c: In function 'mfile':
mbid.c:81: warning: control reaches end of non-void function
file.c: In function 'file_read_config':
file.c:327: warning: 'data' may be used uninitialized in this function

I made a patch which should fix its at all.

Attention! As minimum one warning discover really error (because it's
a typo):

lmc.c: In function 'lmc_failure':
lmc.c:42: warning: suggest parentheses around comparison in operand of
|

My fix:
-    if (*ch=='\n' || *ch=='\t' || *ch=='\r' | *ch=='\v') {
+    if (*ch=='\n' || *ch=='\t' || *ch=='\r' || *ch=='\v') {